// Generated by CoffeeScript 1.6.3
(function() {
  var client, mc;

  mc = require('minecraft-protocol');

  client = mc.createClient({
    host: 'localhost',
    port: 25565,
    username: 'webuser',
    password: null
  });

  client.on('packet', function(p) {
    return console.log(p);
  });

}).call(this);
