// Generated by CoffeeScript 1.6.3
(function() {
  var client, ids, mc, states;

  mc = require('minecraft-protocol');

  client = mc.createClient({
    host: 'localhost',
    port: 25565,
    username: 'webuser',
    password: null
  });

  states = mc.protocol.states;

  ids = mc.protocol.packetIDs.play.toServer;

  client.on('packet', function(p) {
    var name;
    name = mc.protocol.packetNames.play.toClient[p.id];
    if (name.indexOf('entity_') === 0) {
      return;
    }
    return console.log(name, p);
  });

  client.on([states.PLAY, ids.disconnect], function(p) {
    return console.log("Kicked for " + p.reason);
  });

}).call(this);
